/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RedirectIndexRouteImport } from './routes/redirect/index'
import { Route as ContentsIndexRouteImport } from './routes/contents/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectIndexRoute = RedirectIndexRouteImport.update({
  id: '/redirect/',
  path: '/redirect/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsIndexRoute = ContentsIndexRouteImport.update({
  id: '/contents/',
  path: '/contents/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contents': typeof ContentsIndexRoute
  '/redirect': typeof RedirectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contents': typeof ContentsIndexRoute
  '/redirect': typeof RedirectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contents/': typeof ContentsIndexRoute
  '/redirect/': typeof RedirectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contents' | '/redirect'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contents' | '/redirect'
  id: '__root__' | '/' | '/contents/' | '/redirect/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentsIndexRoute: typeof ContentsIndexRoute
  RedirectIndexRoute: typeof RedirectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect/': {
      id: '/redirect/'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents/': {
      id: '/contents/'
      path: '/contents'
      fullPath: '/contents'
      preLoaderRoute: typeof ContentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentsIndexRoute: ContentsIndexRoute,
  RedirectIndexRoute: RedirectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
