/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppIdIndexRouteImport } from './routes/app/$id/index'
import { Route as UserRegisterIdIndexRouteImport } from './routes/user/register/$id/index'
import { Route as UserJoinIdIndexRouteImport } from './routes/user/join/$id/index'
import { Route as UserAuthenticateIdIndexRouteImport } from './routes/user/authenticate/$id/index'

const AppIdIndexRoute = AppIdIndexRouteImport.update({
  id: '/app/$id/',
  path: '/app/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRegisterIdIndexRoute = UserRegisterIdIndexRouteImport.update({
  id: '/user/register/$id/',
  path: '/user/register/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserJoinIdIndexRoute = UserJoinIdIndexRouteImport.update({
  id: '/user/join/$id/',
  path: '/user/join/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAuthenticateIdIndexRoute = UserAuthenticateIdIndexRouteImport.update({
  id: '/user/authenticate/$id/',
  path: '/user/authenticate/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/app/$id': typeof AppIdIndexRoute
  '/user/authenticate/$id': typeof UserAuthenticateIdIndexRoute
  '/user/join/$id': typeof UserJoinIdIndexRoute
  '/user/register/$id': typeof UserRegisterIdIndexRoute
}
export interface FileRoutesByTo {
  '/app/$id': typeof AppIdIndexRoute
  '/user/authenticate/$id': typeof UserAuthenticateIdIndexRoute
  '/user/join/$id': typeof UserJoinIdIndexRoute
  '/user/register/$id': typeof UserRegisterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app/$id/': typeof AppIdIndexRoute
  '/user/authenticate/$id/': typeof UserAuthenticateIdIndexRoute
  '/user/join/$id/': typeof UserJoinIdIndexRoute
  '/user/register/$id/': typeof UserRegisterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app/$id'
    | '/user/authenticate/$id'
    | '/user/join/$id'
    | '/user/register/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app/$id'
    | '/user/authenticate/$id'
    | '/user/join/$id'
    | '/user/register/$id'
  id:
    | '__root__'
    | '/app/$id/'
    | '/user/authenticate/$id/'
    | '/user/join/$id/'
    | '/user/register/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppIdIndexRoute: typeof AppIdIndexRoute
  UserAuthenticateIdIndexRoute: typeof UserAuthenticateIdIndexRoute
  UserJoinIdIndexRoute: typeof UserJoinIdIndexRoute
  UserRegisterIdIndexRoute: typeof UserRegisterIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app/$id/': {
      id: '/app/$id/'
      path: '/app/$id'
      fullPath: '/app/$id'
      preLoaderRoute: typeof AppIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/register/$id/': {
      id: '/user/register/$id/'
      path: '/user/register/$id'
      fullPath: '/user/register/$id'
      preLoaderRoute: typeof UserRegisterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/join/$id/': {
      id: '/user/join/$id/'
      path: '/user/join/$id'
      fullPath: '/user/join/$id'
      preLoaderRoute: typeof UserJoinIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/authenticate/$id/': {
      id: '/user/authenticate/$id/'
      path: '/user/authenticate/$id'
      fullPath: '/user/authenticate/$id'
      preLoaderRoute: typeof UserAuthenticateIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppIdIndexRoute: AppIdIndexRoute,
  UserAuthenticateIdIndexRoute: UserAuthenticateIdIndexRoute,
  UserJoinIdIndexRoute: UserJoinIdIndexRoute,
  UserRegisterIdIndexRoute: UserRegisterIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
