/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserRegisterRouteImport } from './routes/user/register'
import { Route as UserConfirmRouteImport } from './routes/user/confirm'
import { Route as UserAuthenticationRouteImport } from './routes/user/authentication'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRegisterRoute = UserRegisterRouteImport.update({
  id: '/user/register',
  path: '/user/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UserConfirmRoute = UserConfirmRouteImport.update({
  id: '/user/confirm',
  path: '/user/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAuthenticationRoute = UserAuthenticationRouteImport.update({
  id: '/user/authentication',
  path: '/user/authentication',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user/authentication': typeof UserAuthenticationRoute
  '/user/confirm': typeof UserConfirmRoute
  '/user/register': typeof UserRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user/authentication': typeof UserAuthenticationRoute
  '/user/confirm': typeof UserConfirmRoute
  '/user/register': typeof UserRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user/authentication': typeof UserAuthenticationRoute
  '/user/confirm': typeof UserConfirmRoute
  '/user/register': typeof UserRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/user/authentication' | '/user/confirm' | '/user/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/user/authentication' | '/user/confirm' | '/user/register'
  id:
    | '__root__'
    | '/'
    | '/user/authentication'
    | '/user/confirm'
    | '/user/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserAuthenticationRoute: typeof UserAuthenticationRoute
  UserConfirmRoute: typeof UserConfirmRoute
  UserRegisterRoute: typeof UserRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/register': {
      id: '/user/register'
      path: '/user/register'
      fullPath: '/user/register'
      preLoaderRoute: typeof UserRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/confirm': {
      id: '/user/confirm'
      path: '/user/confirm'
      fullPath: '/user/confirm'
      preLoaderRoute: typeof UserConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/authentication': {
      id: '/user/authentication'
      path: '/user/authentication'
      fullPath: '/user/authentication'
      preLoaderRoute: typeof UserAuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserAuthenticationRoute: UserAuthenticationRoute,
  UserConfirmRoute: UserConfirmRoute,
  UserRegisterRoute: UserRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
