/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserNewRouteImport } from './routes/user/new'
import { Route as AuthenticationLoginRouteImport } from './routes/authentication/login'

const UserNewRoute = UserNewRouteImport.update({
  id: '/user/new',
  path: '/user/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationLoginRoute = AuthenticationLoginRouteImport.update({
  id: '/authentication/login',
  path: '/authentication/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/authentication/login': typeof AuthenticationLoginRoute
  '/user/new': typeof UserNewRoute
}
export interface FileRoutesByTo {
  '/authentication/login': typeof AuthenticationLoginRoute
  '/user/new': typeof UserNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/authentication/login': typeof AuthenticationLoginRoute
  '/user/new': typeof UserNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/authentication/login' | '/user/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/authentication/login' | '/user/new'
  id: '__root__' | '/authentication/login' | '/user/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  UserNewRoute: typeof UserNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user/new': {
      id: '/user/new'
      path: '/user/new'
      fullPath: '/user/new'
      preLoaderRoute: typeof UserNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/login': {
      id: '/authentication/login'
      path: '/authentication/login'
      fullPath: '/authentication/login'
      preLoaderRoute: typeof AuthenticationLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  UserNewRoute: UserNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
